# Generated by Django 3.1.3 on 2020-11-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent_category')},
        ),
    ]
